# GitHub Pages config

title: tsl-apple-cloudkit
description: TypeScript library for Apple CloudKit JS v2
author:
  name: Â© TypeScriptLibs
  email: bug@typescriptlibs.org

show_excerpts: false

header_pages:
  - www/downloads.md
  - SECURITY.md
  - LICENSE.md
  - www/all-libraries.md

include:
  - LICENSE.md
  - README.md
  - SECURITY.md
  - www/all-libraries.md
  - www/downoads.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-titles-from-headings

remote_theme: jekyll/minima

minima:
  date_format: "%Y-%m-%d"
  skin: auto
  social_links:
    - { platform: github, user_url: "https://github.com/typescriptlibs/" }
    - { platform: rss,    user_url: "feed.xml" }

titles_from_headings:
  enabled: true
  strip_title: true
  collections: true
