title: Apple CloudKit TypeScript Library
description: CloudKit JS v2 Library for TypeScript
author: Â© TypeScriptLibs
email: bug@typescriptlibs.org
github_username:  typescriptlibs
rss: rss

show_excerpts: false

github:
    private: true

plugins:
 - jekyll-feed
 - jekyll-seo-tag

theme: minima

minima:
  date_format: "%Y-%m-%d"
